# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phonecat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='props',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
