# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecat', '0002_phone_props'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.AddField(
            model_name='phone',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=b'phones'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=b'phones'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=b'phones'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=b'phones'),
        ),
        migrations.AddField(
            model_name='phone',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=b'phones'),
        ),
    ]
