# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonecat', '0003_auto_20160714_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['id']},
        ),
    ]
